services:
  hiei:
    build:
      # both context and dockerfile path
      # set to the root of the repo
      context: ".."
      dockerfile: "./deploy/Dockerfile"
      tags:
        - "localhost:5000/hiei:latest"
      args:
        PLATFORM: ${PLATFORM}
        PROTOC_VERSION: ${PROTOC_VERSION}
    ports:
      - "2112:2112"
      - "8080:8080"
    stop_signal: SIGINT
    #working_dir: "/source"
    #volumes:
    #  - "../pb:/source"
    #command: bash -c "
    #    protoc *.proto --proto_path=.
    #     --go_out=. --go_opt=module=github.com/user/echo-contracts/pb
    #     --go-grpc_out=. --go-grpc_opt=module=github.com/user/echo-contracts/pb
    #    "
  prometheus:
    #build:
    #  context: "../"
    image: prom/prometheus:v2.53.2
    container_name: prometheus
    #healthcheck:
    #  test: ["CMD", "./scripts/phc.sh"]
    #  interval: 10s
    #  timeout: 15s
    #  retries: 10
    #  start_period: 40s
    volumes:
      - ./:/etc/prometheus/
      #- ./deploy/:/etc/prometheus/
      #- ./deploy/prometheus.yml:/etc/prometheus/prometheus.yml
      #- prometheus_data:/prometheus
    command:
      #- '--config.file=/etc/prometheus/prometheus.yml'
      #- '--storage.tsdb.path=/prometheus'
      #- '--web.console.libraries=/usr/share/prometheus/console_libraries'
      #- '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090 # prometheus
      - 9093:9093 # alertmanager
      #- 9000:9000
    stop_signal: SIGINT
    restart: unless-stopped

  grafana:
    depends_on:
      prometheus:
        condition: service_healthy
    image: grafana/grafana:9.3.0
    container_name: grafana
    ports:
      - 3000:3000
    stop_signal: SIGINT
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=grafana
    volumes:
      - ./deploy/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
      - ./grafana:/var/lib/grafana

volumes:
  prometheus_data:
  grafana:



