global:
  scrape_interval:      15s
  evaluation_interval:  15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090', 'localhost:2112']
  - job_name: golang
    metrics_path: /metrics
    static_configs:
      - targets:
        - prometheus:9000
        - hiei:2112
