name: jaganshi

# This rule triggers when the workflow will run
on:
  # run the workflow manually from Actions tab
  workflow_dispatch:

# jobs can run in sequence or parallel in a workflow
jobs:
  # This single job is called "build"
  build:
    # Specify the operating system for the runner job
    runs-on: ubuntu-latest
    env:
      git_hash: $(git rev-parse --short "$GITHUB_SHA")

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # the job gets runned into $GITHUB_WORKSPACE, that is the environment variable for the repo
      - name: Access current repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Build docker image
        run: |
          docker run  -d -p 5000:5000 --name registry registry:2.7
          # The Makefile sets environment variables,
          # retrieved by compose and passed to Dockerfile.
          make
          #docker compose -f ./oci-spec/compose.yml --progress=plain build protogen
          #docker push localhost:5000/protogen:latest
          #podman build -t bubo_builder:latest -f ./utils/busybox/Dockerfile


      - name: Retrieve artifact from docker image
        run: |
          docker run -it --name hiei -d localhost:5000/protogen:latest
          docker cp hiei:./hid ${{ github.workspace }}/artifacts/

      - name: Archive the build artifact
        uses: actions/upload-artifact@v3
        with:
          name: hiei
          # image size: 18.8MB
          # artifact size: 10.7MB
          path: ${{ github.workspace }}/artifacts/hiei
